package interface_adapter.get_loadable_games;

import use_case.get_loadable_games.GetLoadableGamesOutputBoundary;

public class GetLoadableGamesPresenter implements GetLoadableGamesOutputBoundary {
}
